eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8085
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-client/**
      service-id: eureka-client
    api-b:
      path: /api-ribbon/**
      service-id: ribbon
security:
  list: getToken,login,index